### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by SmBe19** [Nighmared/MA#1]
Some things you might want to fix/improve before you submit the game:

 - Remove savegames from git and clear `usrlist.txt` (e.g. choosing user urs will crash the game).
 - Have realistic scores and adequate names in the highscore file (also, this should probably not be in git).
 - Allow speeding up text instead of just skipping it (I might still want to read it but I don't have time to sit through slow crawling text).
 - Run animation is way too fast.
 - If I die and already took the weapon, it does not respawn (I saw in your save file that this is intentional, but I think this is a stupid thing to do). How am I supposed to do anything if I don't have a weapon?
 - Enemies have way too many lives. Check out [this video](https://youtu.be/AJdEqssNZ-U).
 - The imprecise collision detection is really annoying and it is really difficult to jump onto things (e.g. in Level 1 to get the pistol).
 - Not being able to change horizontal movement while in the air is rather annoying and in most games of this type one can move in the air (although slower). This would really help with making the player feel more in control of his character.
 - In Level 1 it's annoying to have to walk back so much once you fall down.
 - Checkpoints to reload from once you die would be quite nice. It sucks to have to start over, even more so to have to edit the save game to be able to get a weapon again.
 - The jumps are way too tight. Maybe increase the jump force slightly? Right now it is kind of annoying to have to try 20 times to jump onto a ledge (which should be rather simple).
 - The shotgun's fire rate is way too low.
 - In Level 3 why do I need to walk across half the level until I get the gun? I lost almost half my lives and there is nothing I could have done to prevent this.
 - The sniper's fire rate is way too low as well.
 - In general there are too many munition "power ups" and not enough health "power ups".
 - Currently it is almost impossible to finish a single level (due to weapon balancing and annoying collision detection).

Cheers

**Comment by Nighmared** [comment]
I‘m gonna finish this another day, but indeed you got some good points. But there is also a lot of points in which i do either partially or totally disagree with you. Before all, how did you get to this project?


Now about your list:
1&2 good ideas gotta change this asap
3 gonna consider this as well
4 noticed this already but ignored it anyways.. doesn‘t have that much of a bad effect to the game itself

5 You still own the weapons you already collected, just select them by the number keys
6 i already know this video and i do understand it‘s message but I don‘t feel like the mechanics it uses is suitable for every type of game so i do rather create difficulty by actual difficulty than by the pure amount of enemies
7 believe me if i tell you that i not only know about this but also tried fixing this for a long time, my advise to that is that if you spam one of the jump keys while keeping to move against a wall, you can kind of climb it (e.g. in lvl 1)
8 Indeed this is possible in most of these games, but that doesn‘t make it anything close being physically correct
9 don‘t fall
10 as i told you, you do keep your weapons once collected so you don‘t really die that often.. i‘m not gonna say anything about the fact that you preferred to cheat instead of looking through the code...
11 i don‘t really see the issue as all one has to do is to make up the correct timing but i‘ll consider that as well
12 this is actually true (same with 13) but as it does deal hella lot of damage i‘d  consider it at least slightly okay balanced 
13 as mentioned you can use the other weapons
14 already mentioned
15 i did notice that as well and i‘ll change that eventually if i happen to have the time for it
16 indeed it is possible by selecting weapons


Thanks after all for the attention you gave my project and your somehow thoughtful recommendations

**Comment by Nighmared** [comment]
Oh.. finished it at once anyways...

**Comment by SmBe19** [comment]
5. I didn't notice that you can change the weapon. I was pretty sure it was not in the help for "Tastenbelegung" but now it is and you didn't add it in the last commit, so I was just not paying attention. My bad.

6. I think the main message is that it is important to improve the game feel. And it makes much more fun (at least in my opinion) to have more enemies with less lives. But this is of course a design decision one has to make for a game.

7. For further projects check out Box2D for physics simulations (there seems to be a port for pygame available). In my earlier projects I also developed the collision detection myself but it is much easier and gives better results to use a library.

8. Most games are not about being physically correct. And this is again a design decision related to "game feel". I think it would feel better to be able to change direction.

10. I did in fact look a bit through the code to find out what needed to be changed to let the weapons respawn (i.e. what to change in the save file). But I did not read every single line to find out how to change weapons. And to be fair the code is not that nice to read :P 

11. This is really a question of how you want to challenge the player. Should it be the fights? The jumping? If you want the jumps to be a challenge you should make them interesting. Right now they should be easy (they at least look like it) but are mostly hard because of wonky controls. If you look at something like Super Mario many jumps look easy and are easy to perform and there are a few hard jumps where you have to have very good timing. But those look difficult (while yours mostly don't) and are challenging in a fun way.

12. Again game feel. If you double the fire rate and half the damage it feel much more fun with the same damage dealt per second.

Most of my remaining points (now that I realized you could change the weapons...) are design choices and can be done either way, I just think the game would feel better with the proposed changes.

If you like to develop games and want to train more (most of those "game feel" decisions come with experience), check out [Ludum Dare](https://ldjam.com/).

Cheers

**Comment by SmBe19** [comment]
Ok, I now managed to finish the first two levels (with the "spamming method"). I think it would already be much more satisfactory to slightly increase jump force (now it seems to be about two blocks height, so maybe to two and a half blocks) so all the two block jumps are not that annoying. I mean to jump onto a ledge right in front of you with no way to fall anywhere should not be that hard. Jumping from platform to platform can be challenging, but just jumping straight up should not be.
